---
- hosts: localhost
  connection: local
  become: false

  pre_tasks: 
  - name: Clear OSX Plist Cache
    shell: killall -u {{ lookup('env', 'USER') }} cfprefsd

  tasks:
  - name: Set autohide to true
    community.general.osx_defaults:
      domain: com.apple.dock
      key: autohide
      type: bool
      value: true
      state: present
    changed_when: True
    notify: Reload Dock

  - name: Set autohide-delay to 0
    community.general.osx_defaults:
      domain: com.apple.dock
      key: autohide-delay
      type: float
      value: 0
      state: present
    changed_when: True
    notify: Reload Dock

  handlers:
    - name: Reload Dock
      shell: killall Dock