---
- hosts: localhost
  connection: local

  tasks:
  - name: Ensure Homebrew is installed
    shell: NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    args:
      creates: /opt/homebrew/bin/brew

  # Required by Lando
  - name: Ensure Rosetta 2 is installed
    shell: |
      /usr/sbin/softwareupdate --install-rosetta --agree-to-license
    args:
      creates: /Library/Apple/usr/share/rosetta

  - name: Updating Homebrew
    homebrew:
      update_homebrew: true
      upgrade: true

  - name: Install core packages via brew casks
    community.general.homebrew_cask:
      name: 
        - 1password
        - alfred
        - appcleaner
        - arc
        - droplr
        - font-fira-code-nerd-font
        - font-hack-nerd-font
        - font-inconsolata-for-powerline
        - google-chrome
        - imageOptim
        - iterm2
        - orbstack
        - postman
        - screenflow
        - lando
        - slack
        - tableplus
        - thingsmacsandboxhelper
        - transmit
        - visual-studio-code
        - zoom
      state: present
      accept_external_apps: true
    
  - name: Install core packages via brew
    community.general.homebrew:
      name: 
        - awscli
        - composer
        - ffmpeg
        - jq
        - mas
        - nvm 
        - php
        - python3
        - terraform
        - tmux
        - wp-cli
      state: present
