---
- hosts: localhost
  connection: local
  become: false

- import_playbook: homebrew.yml

  pre_tasks:
  - name: Check for Command Line Tools
    shell: xcode-select -p | echo $?
    register: xcode_output
    changed_when: False

  - name: Install Command Line Tools
    fail: 
      msg: Command Line Tools should be installed...Run xcode-select --install
    when:
      - xcode_output.stdout != "0"

  tasks: 
  - name: Install tmux
    package:
      name: tmux
      state: present
    tags: tmuxc
