---
- hosts: localhost
  connection: local
  become: false

  tasks:
  - name: Install Mac App Store Apps 
    community.general.mas:
      id: # Use `mas search 'APP_NAME'` to find id.
        - 1569813296 # 1Password for Safari
        - 904280696 # Things 3
        - 441258766 # Magnet

  # - name: Get Show Spotlight Search Value
  #   shell: /usr/libexec/PlistBuddy ~/Library/Preferences/com.apple.symbolichotkeys.plist -c "Print AppleSymbolicHotKeys:64:enabled"
  #   register: ShowSpotlightSearch
  #   changed_when: False

  # - name: debug
  #   debug: 
  #     var: ShowSpotlightSearch
  #     verbosity: 2

  # - name: Set Plist Things
  #   shell: |
  #    /usr/libexec/PlistBuddy ~/Library/Preferences/com.apple.symbolichotkeys.plist -c "Set AppleSymbolicHotKeys:64:enabled false"
  #    /System/Library/PrivateFrameworks/SystemAdministration.framework/Resources/activateSettings -u
  #   when:
  #     -  ShowSpotlightSearch.stdout == "true"
