---
- hosts: localhost
  connection: local
  become: false

  tasks:
  - name: Install Mac App Store Apps 
    community.general.mas:
      id: # Use `mas search 'APP_NAME'` to find id.
        - 1569813296 # 1Password for Safari
        - 904280696 # Things 3
        - 441258766 # Magnet
