---
- hosts: localhost
  connection: local
  become: false

  pre_tasks:
  - name: Ensuring Homebrew Is Installed
    stat:
      path: /usr/local/bin/brew
    register: homebrew_check

  - name: Fail if homebrew is not installed and install_homebrew_if_missing is False
    fail: 
      msg: Homebrew is missing...Install from https://brew.sh/
    when:
      - not homebrew_check.stat.exists
      - not install_homebrew_if_missing

  - name: Installing Homebrew
    shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    when:
      - not homebrew_check.stat.exists
      - install_homebrew_if_missing 

  tasks:
  - name: Updating Homebrew
    homebrew:
      update_homebrew: true
      upgrade: true
    when: homebrew_check.stat.exists
  
  - name: Install core packages via brew casks
    community.general.homebrew_cask:
      name: visual-studio-code
      state: present
      accept_external_apps: true

  - name: Install Extensions
    shell: |
      code --install-extension bierner.markdown-mermaid
      code --install-extension bmewburn.vscode-intelephense-client
      code --install-extension bradlc.vscode-tailwindcss
      code --install-extension breezelin.phpstan
      code --install-extension cssho.vscode-svgviewer
      code --install-extension DavidAnson.vscode-markdownlint
      code --install-extension DotJoshJohnson.xml
      code --install-extension eamodio.gitlens
      code --install-extension EditorConfig.EditorConfig
      code --install-extension formulahendry.auto-close-tag
      code --install-extension formulahendry.auto-rename-tag
      code --install-extension GitHub.codespaces
      code --install-extension GitHub.github-vscode-theme
      code --install-extension jebbs.plantuml
      code --install-extension johnbillion.vscode-wordpress-hooks
      code --install-extension ms-vscode-remote.remote-containers
      code --install-extension ms-vsliveshare.vsliveshare
      code --install-extension naumovs.color-highlight
      code --install-extension neilbrayfield.php-docblocker
      code --install-extension PKief.material-icon-theme
      code --install-extension redhat.vscode-yaml
      code --install-extension sdras.night-owl
      code --install-extension SimplyDanny.modelica
      code --install-extension streetsidesoftware.code-spell-checker
      code --install-extension Tyriar.sort-lines
      code --install-extension valeryanm.vscode-phpsab
      code --install-extension vincaslt.highlight-matching-tag
      code --install-extension Vue.volar
      code --install-extension wayou.vscode-todo-highlight
      code --install-extension whatwedo.twig
      code --install-extension wwm.better-align
      code --install-extension xdebug.php-debug