---
- hosts: localhost
  connection: local
  become: false

  tasks:
  - name: Ensure Homebrew is installed
    shell: NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    args:
      creates: /opt/homebrew/bin/brew

  - name: Updating Homebrew
    homebrew:
      update_homebrew: true
      upgrade: true
  
  - name: Install core packages via brew casks
    community.general.homebrew_cask:
      name: visual-studio-code
      state: present
      accept_external_apps: true

  - name: Install Extensions
    shell: code --install-extension {{ item }}
    register: code_extension
    changed_when: "'was successfully installed' in code_extension.stdout"
    with_items:
    - bierner.markdown-mermaid
    - bmewburn.vscode-intelephense-client
    - bradlc.vscode-tailwindcss
    - breezelin.phpstan
    - chouzz.vscode-better-align
    - davidanson.vscode-markdownlint
    - dotjoshjohnson.xml
    - eamodio.gitlens
    - editorconfig.editorconfig
    - formulahendry.auto-close-tag
    - formulahendry.auto-rename-tag
    - github.codespaces
    - github.copilot
    - github.copilot-chat
    - github.github-vscode-theme
    - hashicorp.terraform
    - jebbs.plantuml
    - johnbillion.vscode-wordpress-hooks
    - mohd-akram.vscode-html-format
    - ms-azuretools.vscode-docker
    - ms-playwright.playwright
    - ms-python.debugpy
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-vscode-remote.remote-containers
    - ms-vsliveshare.vsliveshare
    - naumovs.color-highlight
    - neilbrayfield.php-docblocker
    - phproberto.vscode-php-getters-setters
    - pkief.material-icon-theme
    - redhat.vscode-yaml
    - sdras.night-owl
    - simonsiefke.svg-preview
    - simplydanny.modelica
    - streetsidesoftware.code-spell-checker
    - tyriar.sort-lines
    - valeryanm.vscode-phpsab
    - vincaslt.highlight-matching-tag
    - vue.volar
    - wayou.vscode-todo-highlight
    - whatwedo.twig
    - xdebug.php-debug

  - name: Move VS Code Config
    copy:
      src: ./files/vs-code-settings.json
      dest: /Users/{{ lookup('env', 'USER') }}/Library/Application Support/Code/User/settings.json
      owner: "{{ lookup('env', 'USER') }}"
      force: yes

  - name: Ensure target directory exists
    file:
      path: /Users/{{ lookup('env', 'USER') }}/Library/Application Support/Code/User/snippets/
      state: directory
      mode: '0755'

  - name: Move VS Code Snippets
    copy:
      src: ./files/vs-code-snippets.code-snippets
      dest: /Users/{{ lookup('env', 'USER') }}/Library/Application Support/Code/User/snippets/myGlobal.code-snippets
      owner: "{{ lookup('env', 'USER') }}"
      force: yes
